steps:
  # Build the container image
  - name: 'gcr.io/cloud-builders/docker'
    entrypoint: 'bash'
    args:
      - '-c'
      - |
        docker build -t "gcr.io/$PROJECT_ID/minshumi-frontend:$COMMIT_SHA" --build-arg _COCKROACH_DATABASE_URL=$$_COCKROACH_DATABASE_URL \
                    --build-arg _GOOGLE_AUTH_CLIENT_ID=$$_GOOGLE_AUTH_CLIENT_ID  \
                    --build-arg _GOOGLE_AUTH_CLIENT_SECRET=$$_GOOGLE_AUTH_CLIENT_SECRET  \
                    --build-arg _NEXTAUTH_SECRET=$$_NEXTAUTH_SECRET  \
                    --build-arg _REDIS_NEW_ART_SESSION_URL=$$_REDIS_NEW_ART_SESSION_URL  \
                    .
    secretEnv:
      [
        '_COCKROACH_DATABASE_URL',
        '_GOOGLE_AUTH_CLIENT_ID',
        '_GOOGLE_AUTH_CLIENT_SECRET',
        '_NEXTAUTH_SECRET',
        '_REDIS_NEW_ART_SESSION_URL',
      ]

  # Push the container image to Container Registry
  - name: 'gcr.io/cloud-builders/docker'
    args: ['push', 'gcr.io/$PROJECT_ID/minshumi-frontend:$COMMIT_SHA']

  # Deploy container image to Cloud Run
  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    entrypoint: 'bash'
    args:
      - '-c'
      - |
        gcloud run deploy minshumi-frontend \
          --image gcr.io/$PROJECT_ID/minshumi-frontend:$COMMIT_SHA \
          --region asia-northeast1 \
          --set-secrets=_COCKROACH_DATABASE_URL=cockroach-db-prod-url:1,_GOOGLE_AUTH_CLIENT_ID=google-auth-client-id:1,_GOOGLE_AUTH_CLIENT_SECRET=google-auth-client-secret:1,_NEXTAUTH_SECRET=nextauth-secret:1,_REDIS_NEW_ART_SESSION_URL=redis-new-art-session-url:1

images:
  - 'gcr.io/$PROJECT_ID/minshumi-frontend:$COMMIT_SHA'

availableSecrets:
  secretManager:
    - versionName: projects/megane-s-gcp/secrets/cockroach-db-prod-url/versions/1
      env: '_COCKROACH_DATABASE_URL'
    - versionName: projects/megane-s-gcp/secrets/google-auth-client-id/versions/1
      env: '_GOOGLE_AUTH_CLIENT_ID'
    - versionName: projects/megane-s-gcp/secrets/google-auth-client-secret/versions/1
      env: '_GOOGLE_AUTH_CLIENT_SECRET'
    - versionName: projects/megane-s-gcp/secrets/nextauth-secret/versions/1
      env: '_NEXTAUTH_SECRET'
    - versionName: projects/megane-s-gcp/secrets/redis-new-art-session-url/versions/1
      env: '_REDIS_NEW_ART_SESSION_URL'
