name: Pull Request Check

on: pull_request

permissions:
  checks: write
  contents: write
  issues: write
  pull-requests: write

jobs:
  lint:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [18.x]
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Use Node.js
        uses: actions/setup-node@v2
        with:
          node-version: ${{ matrix.node-version }}
      - name: Install dependencies
        run: yarn install --frozen-lockfile --ignore-scripts
      - name: Generate Prisma client
        run: yarn prisma generate
      - name: Run lint check
        run: yarn lint
      - name: Reviewdog
        uses: reviewdog/action-eslint@v1
        env:
          REVIEWDOG_GITHUB_API_TOKEN: ${{ secrets.GITHUB_TOKEN }}
  check-build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [18.x]
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Use Node.js
        uses: actions/setup-node@v2
        with:
          node-version: ${{ matrix.node-version }}
      - name: Install dependencies
        run: yarn install --frozen-lockfile --ignore-scripts
      - name: Generate Prisma client
        run: yarn prisma generate
      - name: Run build
        run: yarn build
        env:
          COCKROACH_DATABASE_URL: ${{ secrets.COCKROACH_DATABASE_URL }}
          BUSINESS_CARD_IMAGE_SERVER: ${{ secrets.BUSINESS_CARD_IMAGE_SERVER }}
